# -*- coding: utf-8 -*-
"""busradar_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KqfjEZmoeewcC4cmyvjXOtPUMDOOtMRh
"""

import pandas as pd
import json
import requests
import datetime

r = requests.get('https://rest.busradar.conterra.de/prod/fahrzeuge')

json_data = json.loads(r.text)

df = pd.DataFrame(json_data['features'])

from pandas import json_normalize
df = pd.concat([pd.DataFrame(json_data), 
                json_normalize(json_data['features'])], 
                axis=1).drop('features', 1)

df

df[['xkoord','ykoord']] = pd.DataFrame(df['geometry.coordinates'].tolist(), index= df.index)

zeitstempel = datetime.datetime.now().strftime('%Y_%m_%d_%H_%M_utc')

df.to_csv('./csv/'+zeitstempel+'.csv')

